apiVersion: v1
kind: ConfigMap
metadata:
  name: config-client
data:
  config.js: |
    const config = { VUE_APP_ENV_BACKEND: `http://${process.env.FLASK_SERVICE_SERVICE_HOST}:${process.env.FLASK_SERVICE_SERVICE_PORT}` };
    export default config;
