apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapi-deployment
  labels:
    app: flaskapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskapi
  template:
    metadata:
      labels:
        app: flaskapi
    spec:
      containers:
        - name: flaskapi
          image: flask-vue-server:10
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: PG_USER
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: pg_user
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret-config
                  key: pg_password
